### ISSUE TITLE
Adjustments to hot and cold categories from Dr. Chris Bridges

### ISSUE THREAD

**Issue by Abraxas3d** [phase4space/payload-dmt#1]
Feedback from Dr. Chris Bridges:

- [x] "TT&C does not strictly need to be cold redundant"
- [x] "MMIC Amplifiers can be moved to cold redundant because PAs can be switched"

LNA needs to stay hot, strong agreement.

**Comment by yrrapt** [comment]
@cpbridges I am curious about the benefits of actively switching the PAs over a passive power combination topology. 

I think it's a moot point now that I know about the switch matrix needed to connect the multiple antennas. However for my own understanding I would love to explore this a bit more.

To my mind the passive method is much more reliable than an active method for the following reasons:
- There is fully redundant paths on the PA, connectors, harnesses and antenna elements
- There is no single point of failure, by adding the switches the single failure point is just moved there (although you would expect it to be more reliable)
- There is more complexity added, therefore more points of failure, ie. switch power supplies, switch control signals etc.
- Indeed the passive method requires no control at all, it just gracefully degrades without any need for intervention
- The PA power and heat density is lower as it's split between more amplifiers leading to less device stress

As I say, I think this is purely academic now, but in the interest of engineering methodology discussion and knowledge I am curious if there's something I'm missing that favours the cold switching topology?

Cheers,
Thomas

**Comment by cpbridges** [comment]
Hi Thomas, Michelle,

I'm happy for either a splitter or a switch actually! The comment I made was more about payload control - and for safety and testing reasons, there must be method(s) to turn off the transmitter.

There could be holistic reasons (e.g. local QRM affecting other systems, power draw) or local reasons (e.g. overheating, testing).

73s Chris

**Comment by yrrapt** [comment]
Hey Chris,

Thanks for the response.

That's a good point about the need for safety inhibits to prevent RF emissions.  With no battery -spurious RF emissions will be the main hazard to the host spacecraft. 

Cheers,
Thomas
