### ISSUE TITLE
trouble starting the notebook

### ISSUE THREAD

**Issue by Gooseman42** [phase4space/payload-dmt#6]
I am obviously a noob when it comes to Jupyter and its notebook: I have both installed via pip on a VM (Ubuntu 18.04) but seemingly fail to execute the link budget file. When I try to run, I get the following messages:
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a3c0d8a5aef7> in <module>
----> 1 get_ipython().run_line_magic('matplotlib', 'notebook')
      2 get_ipython().run_line_magic('load_ext', 'autoreload')
      3 get_ipython().run_line_magic('autoreload', '2')`

and further down:
`ModuleNotFoundError: No module named 'matplotlib'`

I did however 
`pip3 install matplotlib`
but that did not cure the problem..  I am pretty sure it is a simple fix (likely embarassing..)..

Thanks,
Achim

**Comment by yrrapt** [comment]
Hey Achim,

Looks like matplotlib isn't installed as you surmised.

Often Python 2 and Python 3 are installed side by side. If the Jupyter notebook is using Python 2 then you'll need to use:

```
pip install matplotlib
```

To install the Python 2 version. 

Let me know how you get on, 
Thomas

**Comment by Gooseman42** [comment]
after matplotlib, I had to install next pylink, scipy and itur.. but now I knew what to do.. or at least I thought. Now I have:
`AttributeError: module 'pylink' has no attribute 'Element'`
no idea how to proceed..

**Comment by yrrapt** [comment]
Sounds like progress. 

There seems to be a clash between naming so you'll need to remove pylink and instead install pylink-satcom

**Comment by Gooseman42** [comment]
Thomas,
this seemed to unlock quite some more things. It seems that is run now without errors, but (as I am new to jupyter notebook) I think I do not execute the script properly. If I "restart kernel and re run notebook", it does not seem to do anything for at least 10 minutes (when I stopped it). I am clearly missing something.. sorry for my clumsiness.. This is valid for both the lunar and the GEO case so it is clearly on me.
Thanks! Achim

**Comment by yrrapt** [comment]
Hi Achim,

Good to hear it's running now.

Some of the calculations are quite extensive so it takes a while to run.

In particular the Monto-Carlo analysis takes a long time.  I normally leave it running overnight so I don't know how long it actually takes.

That being said there should be things updating before the Monte-Carlo section.  For example if we look at the GEO notebook. If you start a new notebook, and select the top box and step through each box individually using shift+enter you should see the datarate vs dish size display a graph after 10 minutes or so.  The next cell will be instant as it's just displaying already calculated data.

The other thing you can do is reduce the number of calculations to speed things up.  The last number in a ``np.linspace`` call is the number of points each item is calculated at so you can reduce that to speed things up.  The ``mc_length`` variable changes the number of items in the Monte-Carlo calculation although making it smaller will reduce the statistical accuracy of the results.  Personally I wouldn't really try to use the Monte-Carlo analysis in any kind of interactive mode.

At the moment it's set up to do a lot of calculations to increase the data displayed as a rendered document on GitHub.  It's perfectly sensible (and what I would do) to play with the settings to get a more responsive environment when you're interacting with the notebooks.

**Comment by Gooseman42** [comment]
I see, just need to give the code some more time.. thank you for your support, much appreciated!
